version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show Current Branch
          command: echo ${CURRENT_BRANCH}
      - restore _cache:
          key:
            - app-{{ checksum "package.json" }}	
            - app-
      - run:
          name: Install Dependiencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}

  deploy-to-aws-s3:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show Current Branch
          command: echo {$CURRENT_BRANCH}
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt -qq update -y
            sudo apt install awscli -y
            sudo apt install python-pip python-dev build-essential -y
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build Successful"
      -run:
          name: Deploy to AWS S3
          commmands:
            if [ "${CURENT_BRANCH}" == "master" ]
            then 
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_PRODUCTION} --delete
            elif [ "${CURENT_BRANCH}" == "staging" ]
            then 
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_STAGING} --delete
            else 
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_BUCKET_DEV} --delete
            fi

  deploy-to-aws-cloudfront:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show Current Branch
          command: echo {$CURRENT_BRANCH}
      - run:
          name: Install AWS CLI
          working_directory: /
          command: |
            sudo apt -qq update -y
            sudo apt install awscli -y
            sudo apt install python-pip python-dev build-essential -y
      - run:
          name: Build Project
          command: |
          npm install
          npm run build
          cd build
          zip ../build.zip -r * .[^.]*
          echo "Build Successful"
      -run:
          name: Deploy to AWS Cloudfront
          commmands:
            aws configure set preview.cloudfront
            if [ "${CURENT_BRANCH}" == "master" ]
            then 
              aws cloudfront create-invalidation --distribution-id ${PROD_DISTRIBUTION_ID} --paths/\*
            elif [ "${CURENT_BRANCH}" == "staging" ]
            then 
              aws cloudfront create-invalidation --distribution-id ${STG_DISTRIBUTION_ID} --paths/\*
            else 
              aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --paths/\*  
            
            fi

workflows:
  build_and_deploy:
    jobs:
      - build
      - deployto-aws-s3:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master
      - deployto-aws-cloudfront:
          requires:
            - deployto-aws-s3
          filters:
            branches:
              only:
                - develop
                - staging
                - master
